# Use the official Node.js image.
FROM node:18-alpine

# Create and change to the app directory.
WORKDIR /app

# Install app dependencies.
COPY package*.json ./
RUN npm install --omit=dev

# Copy the app files.
COPY . .

# Build the TypeScript code
RUN npm run build

# Set environment variables (optional, for local testing)
ENV PORT=3000
ENV DATABASE_URL="postgresql://postgres:sam@localhost:5432/blog"
ENV SECRET_KEY="edrtfgzuhjidfgbhjnmkfghjnk"

# Expose the port the app runs on.
EXPOSE 3000

# Run the app.
CMD ["node", "dist/index.js"]
