[build]
  builder = "Docker"
  dockerfile = "Dockerfile"
  args = { NODE_ENV = "production" }

[env]
  PORT = "3000"
  DATABASE_URL = { fromSecret = "DATABASE_URL" }
  SECRET_KEY = { fromSecret = "SECRET_KEY" }

[[services]]
  name = "backend"
  ports = [{ internal_port = 3000, external_port = 3000 }]
